# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='lables',
            field=models.ManyToManyField(blank=True, to='events.EventLabel'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='review_nmb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_best_end',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_best_start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_end',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_start',
            field=models.TimeField(blank=True),
        ),
    ]
