# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170729_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time_best_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_best_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
